# Generated by Django 4.1.6 on 2023-02-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0003_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/default.png', upload_to='profile_picture'),
        ),
    ]
